### ISSUE TITLE
Fastprogress callback

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/pytorch-lightning-bolts#2]
## 🚀 Feature
Copied from https://github.com/PyTorchLightning/pytorch-lightning/issues/1500 by @tcwalther

Use https://github.com/fastai/fastprogress instead of tqdm for displaying progress bars.

### Motivation

tqdm doesn't work well with Jupyter Lab. This creates issues with pytorch-lightning's progress bars, where each validation bar creates a newline in the cell output: #1399. This is a well-known issue in jupyter-widgets: https://github.com/jupyter-widgets/ipywidgets/issues/1845

The Fast.ai people developed [fastprogress](https://github.com/fastai/fastprogress) as a replacement for exactly this reason.

### Pitch

Option to replace tqdm with fastprogress.

### Alternatives

The alternative is to wait for jupyter-widgets to fix the issue on their side. Given that this issue has been around since November 2017, I'm not too hopeful that it will happen, though. It looks like this would require major design changes in ipywidgets and/or jupyter-lab.

### Additional context

Motivated by #1399.

**Comment by awaelchli** [comment]
Now that we have the progress bar as callback, we should be able to easily replace tqdm with fastprogress and provide an alternative callback.

**Comment by williamFalcon** [comment]
but we don't want to add fastai as a dependency

**Comment by Borda** [comment]
`fastprogress` is separate repo/package https://pypi.org/project/fastprogress

**Comment by awaelchli** [comment]
I played around a bit with fastprogress, and found some shortcomings. 
1. It does not support infinite iterators (it needs to call len), which for us is not good because we support iterable datasets of arbitrary/variable/infinite length. 
2. Does not properly display in PyCharm without going into settings and changing console behaviour. 
3. Cannot set the total/iterator after initializing the progressbar. 
4. Cannot manually update the progress (at least I couldn't find out how) and instead can only be directly applied in a loop. This is not practical for us since the callback is independent of the training loop. 

It may be nicer in notebooks, but overall imo it is inferior to tqdm. 
At this point, I don't really know a good way integrate it into PL.

**Comment by williamFalcon** [comment]
nice makes sense. 

maybe we should look at extending tqdm to work well with notebooks?

**Comment by Kshitij09** [comment]
Just want to share my experience:

> I don't really know a good way to integrate it into PL.

I had tried to integrate it in the past and yes, it falls short for the points listed by @awaelchli 

> maybe we should look at extending tqdm to work well with notebooks?

This looks like a good idea! all we need is the ability to print between the two progress bars. The master progress_bar will serve as a complete training progress (max=no. of epochs) and the child will serve the current epoch progress. Once we've the ability to write between the progress bars, I'll be able to integrate my [PrintCallback](https://gist.github.com/Kshitij09/eb95bd6667e3b29c649bf95ebb9e1fc7)
