### ISSUE TITLE
Where is the loggers.TrainsLogger?

### ISSUE THREAD

**Issue by igormq** [PyTorchLightning/pytorch-lightning-bolts#249]
Hey folks, you removed the loggers from v.0.2.0 to v0.2.1 and migrate all loggers to the core. However, I couldn't find the TrainsLogger. What did happen?

Thanks!

**Comment by bmartinn** [comment]
@Borda could you help? I could not locate it either...

**Comment by Borda** [comment]
> @Borda could you help? I could not locate it either...

@williamFalcon ^^

**Comment by NumesSanguis** [comment]
Just ran into this issue. Upgraded my code for PyTorch Lightning 1.0.0rc4 and also updated Bolts to match it. Suddenly my code doesn't run because the Trains Logger is gone. I traced the relevant commit to this one: https://github.com/PyTorchLightning/pytorch-lightning-bolts/commit/91393eaa2751dc58c26cec6581aba19d63fa42f8

I hope that Lightining (Bolts) have plans for a more robust review processes, involving multiple people, before things are removed from master? Or least clearer communication to the relevant 3rd parties, because over at Trains they didn't know how this happened. And this already occurred before when the Trains logger was moved (due to a perceived issue with their code) from Lightning to Bolts, without giving them a chance to comment on it:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/86

**Comment by williamFalcon** [comment]
The Trains logger was moved to bolts a long time ago. the code is still available there. We needed to stabilize 1.0.0 and trains was causing a lot of issues on our build.

Please open the issue there so we can take a look at it

**Comment by Ingwar** [comment]
@williamFalcon , sorry, I'm confused here. As far as I understand, this is an issue about disappearance of Trains logger from bolts, not from the main lightning. So, it's **unavailable** in the latest release of pytorch-lightning-bolts and it's unclear, was it a mistake or a deliberate decision. Could you, please, shed a bit of light on it ? :)

**Comment by edenlightning** [comment]
As communicated offline, we are moving some support outside of the repository, but hope to resolve this very soon!

**Comment by bmartinn** [comment]
@williamFalcon 
> Please open the issue there so we can take a look at it

Okay, I will PR the TrainsLogger in the main repo, back with the other loggers. It seems 'bolts' is now more of a recipe-book for  SOTA models, which definitely is not the right place for loggers to be.

**Comment by williamFalcon** [comment]
@bmartinn, as @edenlightning mentioned, we are not looking to add loggers back into the main lightning repo because of the maintenance cost on our end. We think it would be great for you to add that integration on your end. @edenlightning  can talk you through the details of what that looks like.

looking forward to making sure your users have a good experience!

**Comment by bmartinn** [comment]
Well guys I come bearing good news :D
@williamFalcon forgot to mention that starting PL v1.0 all logs are automatically logged by default to Tensorboard.
Now since `train` automagically connects with TB (as well as other frameworks) , it means there is no need for any specific logger whatsoever.

Just create a `trains` Task and you are good to go:
```
from trains import Task
...
if __name__ == '__main__':
    Task.init(project_name="examples", task_name="lightning checkpoint tensorboard and argparse")
```

For example, I took the [mnist](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/mnist.py) example from the PL repo, and added the `Task.init` line.

With that, any call to `log(...)` will be automatically logged by both the TB and the `trains-server` (see [scalars](https://demoapp.trains.allegro.ai/projects/5af31bb1183d4bb19716b863c0381f35/experiments/52e2cf9dcbcb4a3285818e3c922d7ca2/output/metrics/scalar), [console](https://demoapp.trains.allegro.ai/projects/5af31bb1183d4bb19716b863c0381f35/experiments/52e2cf9dcbcb4a3285818e3c922d7ca2/output/log))
`trains` also automatically logs the `argparse` so you have your full configuration logged as well (see [configuration](https://demoapp.trains.allegro.ai/projects/5af31bb1183d4bb19716b863c0381f35/experiments/52e2cf9dcbcb4a3285818e3c922d7ca2/hyper-params/hyper-param/Args)).
Obviously the full environment (code/git/packages) is also viewable ([execution details](https://demoapp.trains.allegro.ai/projects/5af31bb1183d4bb19716b863c0381f35/experiments/52e2cf9dcbcb4a3285818e3c922d7ca2/execution))
Lastly, since all torch.save/load commands are logged, you can see all your model checkpoints (see [models](https://demoapp.trains.allegro.ai/projects/5af31bb1183d4bb19716b863c0381f35/models/869de071a0824fde805913ccc4776289/general)) 
(as usual if you pass `output_uri='s3://bucket/dir'` to Task.init, these models will be automatically uploaded to a dedicated directory in the selected bucket, and of course this also applies for `gs://`, `azure://`, `http://` or even just a shared folder)

Feel free to test with the latest RC, also verified that running remotely with [trains-agent](https://github.com/allegroai/trains-agent) allows you to override any if the `argparse` arguments, as well as the `output_uri`.
```
pip install trains==0.16.3rc0
```

BTW:
We will be working on an even better Logger solution, more on that in the near future :train2:  :smile:

**Comment by NumesSanguis** [comment]
@bmartinn Thanks for the update! Does `trains==0.16.3rc0` work with Trains Server v0.16.1?

**Comment by bmartinn** [comment]
@NumesSanguis `trains` will support any combination of python package and `trains-server` , otherwise how could you reproduce old experiments :) 
BTW: There is nothing special in version `0.16.3rc0` it is just the latest one, so I tested it with it. Any `trains` version should basically work the same way :smiley:
