### ISSUE TITLE
Should MoCo be enqueuing validation batches?

### ISSUE THREAD

**Issue by florisdf** [PyTorchLightning/pytorch-lightning-bolts#419]
# 🐛  Bug (?)
Not sure about this, but it seems strange to me that validation batches are also being enqueued in the MoCo queue ([this line](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/7c2e651a8a8faee2dfdf6c60b196ad071227b910/pl_bolts/models/self_supervised/moco/moco2_module.py#L252)). Shouldn't we only enqueue training batches?

Or am I missing something here?

**Comment by ananyahjha93** [comment]
@florisdf let me take a look at moco! Thanks for reporting this.

**Comment by kcetskcaz** [comment]
This should be revived as this causes data leakage since the validation embeddings are unintentionally enqueued and used for subsequent training steps. Unless your validation and training datasets are the same (which is often not the case), this will (and has, at least for me) cause a massive headache for many users that naively assumed that the validation metrics were purely reported without giving much thought as to how. 

A suggested fix would be to maintain a separate validation queue (either throughout training, or initialized/de-initialized each validation pass), or ignore the validation dataset altogether if it differs from the training data.
