### ISSUE TITLE
Wrong import in tutorials for DQN

### ISSUE THREAD

**Issue by drozzy** [PyTorchLightning/pytorch-lightning-bolts#454]
Here: https://pytorch-lightning-bolts.readthedocs.io/en/latest/reinforce_learn.html#dqn-results

It should be:
`from pl_bolts.models.rl.dqn_model import DQN`

and not:
`from pl_bolts.models.rl import DQN`

**Comment by hassiahk** [comment]
Hey @drozzy, you can actually do it both ways. In the `__init__.py`, `DQN` is already imported like below so you can also import like `from pl_bolts.models.rl import DQN` instead of `from pl_bolts.models.rl.dqn_model import DQN`.
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/58536c260e7877c8c75dfccfaa58acee4fdc2ae1/pl_bolts/models/rl/__init__.py#L1-L3

**Comment by drozzy** [comment]
Oh, strange. I got import error when I did it the tutorial way.

**Comment by drozzy** [comment]
Nevermind, it works now. Thanks!
